chat/urls.py
from django.urls import path
from . import views

app_name = "chat"

urlpatterns = [
    path("", views.chat_list_view, name="list"),                
    path("<int:dialog_id>/", views.dialog_view, name="dialog"), 
    path("api/unread/", views.check_unread, name="check_unread"),
    path("start/<int:psychologist_id>/", views.start_dialog, name="start"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import redirect

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('authorization.urls')),
    path('booking/', include('booking.urls')),
    path('profile/', include('profiles.urls')),
    path('chat/', include('chat.urls')),
    path("hotlines/", include('hotlines.urls'), name="hotlines")
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

main/urls.py
from django.urls import path, include
from django.contrib import admin
from . import views

urlpatterns = [
    path('', views.Home, name='home'),
]

main/models.py
from django.db import models

# Create your models here.

main/templates/shared/footer.html
<footer class="footer">
    <p>E-Psycholog © 2025 — всі права захищені</p>
</footer>

main/templates/shared/header.html
{% load static %}
<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700&family=MuseoModerno:wght@300;400;500;600;700&display=swap" rel="stylesheet">


<header class="header">
    <div class="header-content">

        <div class="logo">
            <img src="{% static 'shared/media/logo.svg' %}" alt="E-Psycholog Logo" class="logo-img">
            <span class="logo-text">E-Psycholog</span>
        </div>

  
        <div class="header-right">
        </div>

    </div>
</header>

main/templates/shared/sidebar.html
{% load static %}
<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700&family=MuseoModerno:wght@300;400;500;600;700&display=swap" rel="stylesheet">

<nav class="sidebar">

  <ul class="nav-menu">

    <li class="nav-item" data-url="{% url 'profile_router' %}">
        <a href="{% url 'profile_router' %}" class="nav-link">
            <img src="{% static 'shared/media/personal-collection.svg' %}" data-active-icon="{% static 'shared/media/personal-collection-green.svg' %}" class="nav-icon">
            Мій профіль
        </a>
    </li>

    <li class="nav-item" data-url="/records/">
        <a href="#" class="nav-link has-submenu">
            <img src="{% static 'shared/media/notebook.svg' %}" data-active-icon="{% static 'shared/media/notebook-green.svg' %}" class="nav-icon">
            Мої записи
        </a>

        <ul class="submenu">
            <li>
                <a href="{% url 'booking_history' %}" class="nav-link">
                    <img src="{% static 'shared/media/history.svg' %}" data-active-icon="{% static 'shared/media/history-green.svg' %}" class="nav-icon">
                    Історія записів
                </a>
            </li>

            <li>
                <a href="{% url 'booking_router' %}" class="nav-link">
                    <img src="{% static 'shared/media/notebook-and-pen.svg' %}" data-active-icon="{% static 'shared/media/notebook-and-pen-green.svg' %}" class="nav-icon">
                    Бронювання
                </a>
            </li>
        </ul>
    </li>

    <li class="nav-item" data-url="/chats/">
        <a href="{% url 'chat:list' %}" class="nav-link">
            <img src="{% static 'shared/media/message.svg' %}" data-active-icon="{% static 'shared/media/message-green.svg' %}" class="nav-icon">
            Чати
            <span id="chat-unread-dot" class="unread-dot" style="display:none;"></span>
        </a>
    </li>

    <li class="nav-item" data-url="{% url 'psychologists_list' %}">
        <a href="{% url 'psychologists_list' %}" class="nav-link">
            <img src="{% static 'shared/media/id-card-h.svg' %}" data-active-icon="{% static 'shared/media/id-card-h-green.svg' %}" class="nav-icon">
            Психологи
        </a>
    </li>

    <li class="nav-item" data-url="/hotlines/">
        <a href="{% url 'hotlines' %}" class="nav-link">
            <img src="{% static 'shared/media/phone-telephone.svg' %}" data-active-icon="{% static 'shared/media/phone-telephone-green.svg' %}" class="nav-icon">
            Гарячі лінії
        </a>
    </li>

  </ul>

  <div class="logout-block">
      <a href="{% url 'logout' %}" class="logout-btn">
          <img src="{% static 'shared/media/logout.svg' %}" class="logout-icon">
          Вийти
      </a>
  </div>

</nav>

<script src="{% static 'shared/js/sidebar.js' %}"></script>